export default function() {
  return {
    apiary: null,
    editing: false,
    apiaries: [
      {
        id: 1,
        title: 'Backyard',
        city: 'Driebergen',
        lastvisit: 'today',
        hives: [
          {
            id: 1,
            honey: 4,
            brood: 2,
            frames: 10,
            color: 'red',
          },
          {
            id: 2,
            honey: 1,
            brood: 3,
            frames: 15,
            color: 'purple',
          },
        ],
        photo: true,
        warning: true,
      },
      {
        id: 2,
        title: 'Garden',
        city: 'Utrecht',
        lastvisit: 'yesterday',
        hives: [
          {
            id: 3,
            honey: 2,
            brood: 2,
            frames: 5,
            color: 'green',
          },
          {
            id: 4,
            honey: 1,
            brood: 5,
            frames: 15,
            color: 'brown',
          },
          {
            id: 5,
            honey: 1,
            brood: 5,
            frames: 15,
            color: 'brown',
          },
          {
            id: 6,
            honey: 1,
            brood: 5,
            frames: 15,
            color: 'brown',
          },
          {
            id: 7,
            honey: 1,
            brood: 5,
            frames: 15,
            color: 'brown',
          },
          {
            id: 8,
            honey: 1,
            brood: 5,
            frames: 15,
            color: 'brown',
          },
          {
            id: 9,
            honey: 1,
            brood: 5,
            frames: 15,
            color: 'brown',
          },
          {
            id: 10,
            honey: 1,
            brood: 5,
            frames: 15,
            color: 'brown',
          },
          {
            id: 11,
            honey: 1,
            brood: 5,
            frames: 15,
            color: 'brown',
          },
          {
            id: 12,
            honey: 1,
            brood: 5,
            frames: 15,
            color: 'brown',
          },
        ],
        photo: true,
      },
      {
        id: 3,
        title: 'Lakeside',
        city: 'Madison',
        lastvisit: 'last week',
        hives: [
          {
            id: 13,
            honey: 2,
            brood: 2,
            frames: 10,
            color: 'cyan',
          },
          {
            id: 14,
            honey: 1,
            brood: 3,
            frames: 15,
            color: 'blue',
          },
        ],
        photo: true,
        warning: true,
        shared: true,
      },
      {
        id: 4,
        title: 'Mountain',
        city: 'Geneva',
        lastvisit: '3 months ago',
        hives: [
          {
            id: 15,
            honey: 2,
            brood: 2,
            frames: 10,
            color: 'orange',
          },
          {
            id: 16,
            honey: 1,
            brood: 3,
            frames: 15,
            color: 'yellow',
          },
          {
            id: 17,
            honey: 2,
            brood: 2,
            frames: 15,
            color: 'yellow',
          },
          {
            id: 18,
            honey: 5,
            brood: 3,
            frames: 10,
            color: 'red',
          },
          {
            id: 19,
            honey: 2,
            brood: 2,
            frames: 15,
            color: 'deep-purple',
          },
          {
            id: 20,
            honey: 5,
            brood: 3,
            frames: 10,
            color: 'red',
          },
        ],
        shared: true,
      },
    ],
  }
}
